//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zentralwerkstatt.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zentralwerkstatt.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server={0};user={1};password=;database={2}.
        /// </summary>
        internal static string preConnectionString {
            get {
                return ResourceManager.GetString("preConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server={0};port={1};user={2};password=;database={3}.
        /// </summary>
        internal static string preConnectionStringPort {
            get {
                return ResourceManager.GetString("preConnectionStringPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?php
        ///
        ///	$link = &quot;{0}&quot;;
        ///	$user = &quot;{1}&quot;;
        ///	if ($_POST[&apos;rootPass&apos;] == &apos;{2}&apos;) $password = &quot;{3}&quot;;
        ///	$dbname = &quot;{4}&quot;;
        ///	
        ///	$conn = mysqli_connect($link,$user,$password,$dbname);
        ///	if($_POST[&apos;url&apos;] == &apos;check_connection&apos;) {
        ///		if(!is_object($conn)) 
        ///		{
        ///			echo &apos;0&apos;;
        ///			exit;
        ///		}
        ///		else echo &apos;1&apos;;
        ///	}else if ($_POST[&apos;url&apos;] == &apos;login&apos;) {
        ///		$sql = &apos;SELECT DISTINCT passwort FROM benutzer WHERE benutzername = &quot;&apos; . $_POST[&apos;user&apos;] . &apos;&quot;&apos;;
        ///		if ($result = $conn-&gt;query($sql)) #sql-anfrage ausführen und in Variable s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string preUebergabeString {
            get {
                return ResourceManager.GetString("preUebergabeString", resourceCulture);
            }
        }
    }
}
